[package]
name = "mohe_ji_step1"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.33"
egui = "0.33"
image = "0.25"
rfd = "0.15"
base64 = "0.22"

[build-dependencies]
winresource = "0.1"
winres = "0.1"

[profile.release]
opt-level = 3
lto = true
codegen-units = 1
panic = 'abort'
strip = true
